image: golang:1.21.0-bullseye

stages:
  - build
  - upload

variables:
  DISTR: bullseye
  APT_LOCAL_REPO: imedia-hpbx-testing-${DISTR}
  APT_DIR: imedia-hpbx-testing-${DISTR}
  APT_REPO: imedia-hpbx-testing
  DEB_DEVEMAIL: hpbxdevteam@intermedia.net
  DEB_PACKAGE_NAME: aproxy
  DEB_PACKAGE_VERSION: "1.0.${CI_PIPELINE_ID}"


build:
  stage: build
  tags: [golang]
  script:
    - make build_linux
    - make deb
  artifacts:
    expire_in: 1 days
    paths:
      - "*amd64.deb"
  only:
    - master

upload:debian10:
  stage: upload
  tags: [apt]
  dependencies:
    - build
  needs:
    - build
  script:
    - make pushdeb
  only:
    - master