name: Test and coverage

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run coverage
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

